export const BANNER_SLIDES = "BANNER_SLIDES";
export const NAVITEM = "NAVITEM";
export const EXPLORE_SLIDES = "EXPLORE_SLIDES";
export const GEAR_SLIDES = "GEAR_SLIDES";
export const CHANGE_LOGIN_SIGNIN = "CHANGE_LOGIN_SIGNIN";
